\begin{quote}
Retry a promise-\/returning or async function \end{quote}
It does exponential backoff and supports custom retry strategies for failed operations.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9975}{}\doxysection{Install}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9975}

\begin{DoxyCode}{0}
\DoxyCodeLine{\$ npm install p-\/retry}

\end{DoxyCode}
\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9976}{}\doxysection{Usage}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9976}

\begin{DoxyCode}{0}
\DoxyCodeLine{const pRetry = require('p-\/retry');}
\DoxyCodeLine{const fetch = require('node-\/fetch');}
\DoxyCodeLine{}
\DoxyCodeLine{const run = async () => \{}
\DoxyCodeLine{    const response = await fetch('https://sindresorhus.com/unicorn');}
\DoxyCodeLine{}
\DoxyCodeLine{    // Abort retrying if the resource doesn't exist}
\DoxyCodeLine{    if (response.status === 404) \{}
\DoxyCodeLine{        throw new pRetry.AbortError(response.statusText);}
\DoxyCodeLine{    \}}
\DoxyCodeLine{}
\DoxyCodeLine{    return response.blob();}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async () => \{}
\DoxyCodeLine{    console.log(await pRetry(run, \{retries: 5\}));}
\DoxyCodeLine{\})();}

\end{DoxyCode}
\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9977}{}\doxysection{API}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9977}
\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9978}{}\doxysubsection{p\+Retry(input, options?)}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9978}
Returns a {\ttfamily Promise} that is fulfilled when calling {\ttfamily input} returns a fulfilled promise. If calling {\ttfamily input} returns a rejected promise, {\ttfamily input} is called again until the maximum number of retries is reached. It then rejects with the last rejection reason.

Does not retry on most {\ttfamily Type\+Errors}, with the exception of network errors. This is done on a best case basis as different browsers have different \href{https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch\#Checking_that_the_fetch_was_successful}{\texttt{ messages}} to indicate this. See \href{https://github.com/whatwg/fetch/issues/526\#issuecomment-554604080}{\texttt{ whatwg/fetch\#526 (comment)}}\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9979}{}\doxysubsubsection{input}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9979}
Type\+: {\ttfamily Function}

Receives the current attempt number as the first argument and is expected to return a {\ttfamily Promise} or any value.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9980}{}\doxysubsubsection{options}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9980}
Type\+: {\ttfamily object}

Options are passed to the \href{https://github.com/tim-kos/node-retry\#retryoperationoptions}{\texttt{ {\ttfamily retry}}} module.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9981}{}\doxyparagraph{on\+Failed\+Attempt(error)}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9981}
Type\+: {\ttfamily Function}

Callback invoked on each retry. Receives the error thrown by {\ttfamily input} as the first argument with properties {\ttfamily attempt\+Number} and {\ttfamily retries\+Left} which indicate the current attempt number and the number of attempts left, respectively.


\begin{DoxyCode}{0}
\DoxyCodeLine{const run = async () => \{}
\DoxyCodeLine{    const response = await fetch('https://sindresorhus.com/unicorn');}
\DoxyCodeLine{}
\DoxyCodeLine{    if (!response.ok) \{}
\DoxyCodeLine{        throw new Error(response.statusText);}
\DoxyCodeLine{    \}}
\DoxyCodeLine{}
\DoxyCodeLine{    return response.json();}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async () => \{}
\DoxyCodeLine{    const result = await pRetry(run, \{}
\DoxyCodeLine{        onFailedAttempt: error => \{}
\DoxyCodeLine{            console.log(`Attempt \$\{error.attemptNumber\} failed. There are \$\{error.retriesLeft\} retries left.`);}
\DoxyCodeLine{            // 1st request => Attempt 1 failed. There are 4 retries left.}
\DoxyCodeLine{            // 2nd request => Attempt 2 failed. There are 3 retries left.}
\DoxyCodeLine{            // â€¦}
\DoxyCodeLine{        \},}
\DoxyCodeLine{        retries: 5}
\DoxyCodeLine{    \});}
\DoxyCodeLine{}
\DoxyCodeLine{    console.log(result);}
\DoxyCodeLine{\})();}

\end{DoxyCode}


The {\ttfamily on\+Failed\+Attempt} function can return a promise. For example, you can do some async logging\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{const pRetry = require('p-\/retry');}
\DoxyCodeLine{const logger = require('./some-\/logger');}
\DoxyCodeLine{}
\DoxyCodeLine{const run = async () => \{ â€¦ \};}
\DoxyCodeLine{}
\DoxyCodeLine{(async () => \{}
\DoxyCodeLine{    const result = await pRetry(run, \{}
\DoxyCodeLine{        onFailedAttempt: async error => \{}
\DoxyCodeLine{            await logger.log(error);}
\DoxyCodeLine{        \}}
\DoxyCodeLine{    \});}
\DoxyCodeLine{\})();}

\end{DoxyCode}


If the {\ttfamily on\+Failed\+Attempt} function throws, all retries will be aborted and the original promise will reject with the thrown error.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9982}{}\doxysubsection{p\+Retry.\+Abort\+Error(message)}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9982}
\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9983}{}\doxysubsection{p\+Retry.\+Abort\+Error(error)}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9983}
Abort retrying and reject the promise.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9984}{}\doxysubsection{message}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9984}
Type\+: {\ttfamily string}

Error message.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9985}{}\doxysubsection{error}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9985}
Type\+: {\ttfamily Error}

Custom error.\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9986}{}\doxysection{Tip}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9986}
You can pass arguments to the function being retried by wrapping it in an inline arrow function\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{const pRetry = require('p-\/retry');}
\DoxyCodeLine{}
\DoxyCodeLine{const run = async emoji => \{}
\DoxyCodeLine{    // â€¦}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async () => \{}
\DoxyCodeLine{    // Without arguments}
\DoxyCodeLine{    await pRetry(run, \{retries: 5\});}
\DoxyCodeLine{}
\DoxyCodeLine{    // With arguments}
\DoxyCodeLine{    await pRetry(() => run('ðŸ¦„'), \{retries: 5\});}
\DoxyCodeLine{\})();}

\end{DoxyCode}
\hypertarget{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9987}{}\doxysection{Related}\label{md__c___users_vaishnavi_jadhav__desktop__developer_code_mean_stack_example_client_node_modules_p_retry_readme_autotoc_md9987}

\begin{DoxyItemize}
\item \href{https://github.com/sindresorhus/p-timeout}{\texttt{ p-\/timeout}} -\/ Timeout a promise after a specified amount of time
\item \href{https://github.com/sindresorhus/promise-fun}{\texttt{ Moreâ€¦}} 
\end{DoxyItemize}